### PR TITLE
Fix running with Python 3.9

### PR DESCRIPTION
**Pull request by yan12125**
Since Python 3.9 [1], codecs names are normalized in a different way.

[1] https://github.com/python/cpython/pull/15092

### CODE REVIEW

**Comment by yan12125** [comment]
@eight04 Could you have a look?

**Comment by eight04** [comment]
It seems that this repo hasn't migrated to travis-ci.com. I'll just add Github action to this PR.

**Comment by eight04** [comment]
Hmm do I have to merge it to make it run?

**Comment by yan12125** [comment]
> Hmm do I have to merge it to make it run?

Dunno, either.  😅 Glad to see GitHub actions eventually work 🎉

**Pull request merged**
